name: syscoin-core
version: 4.1.0.0
summary:   peer-to-peer network based digital currency
description: |
  Syscoin is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict

apps:
  daemon:
    command: syscoind
    plugs: [network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/syscoin-core/common/.syscoin/ instead of
      # ~/snap/syscoin-core/current/.syscoin/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch syscoin-qt
    plugs: [network, network-bind, desktop, x11]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: syscoin-cli
    plugs: [network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  syscoin-core:
    plugin: nil
    override-build: | 
      env | grep SNAP
      wget https://syscoincore.org/bin/syscoin-core-${SNAPCRAFT_PROJECT_VERSION}/SHA256SUMS.asc
      wget https://syscoincore.org/bin/syscoin-core-${SNAPCRAFT_PROJECT_VERSION}/syscoin-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      wget https://syscoincore.org/bin/syscoin-core-${SNAPCRAFT_PROJECT_VERSION}/syscoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "58c6aa349570ffd8137d3a5cd576e83aedcdbe6bdcb2993835b5cd004758f15b  SHA256SUMS.asc" | sha256sum --check
      sha256sum --ignore-missing --check SHA256SUMS.asc
      tar -xvf syscoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      tar -xvf syscoin-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      echo "Running tests ..."
      syscoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_syscoin
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin syscoin-${SNAPCRAFT_PROJECT_VERSION}/bin/syscoind
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin syscoin-${SNAPCRAFT_PROJECT_VERSION}/bin/syscoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin syscoin-${SNAPCRAFT_PROJECT_VERSION}/bin/syscoin-cli
      wget https://raw.githubusercontent.com/syscoin/syscoin/master/share/pixmaps/syscoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps syscoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
